<?php

namespace App\Console\Commands;

use Illuminate\Console\Command;

class changeTraductions extends Command
{
    
    const BASE_PATH = "C:\wamp64\www\storezap\stock\\";

    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'traduction:change';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Command description';

    protected $toReplace = [
        'Total'                                                 =>  'total',
        'Action'                                                =>  'action',
        'Deposit Add'                                           =>  'deposit_add',
        'Select Customer'                                       =>  'select_customer',
        'Amount'                                                =>  'amount',
        'Add Deposit'                                           =>  'add_deposit',
        'Deposit Update'                                        =>  'deposit_update',
        'Update Deposit'                                        =>  'update_deposit',
        'Customer Deposit'                                      =>  'customer_deposit',
        'Print Barcode/Label '                                  =>  'print_barcode/label',
        'Products'                                              =>  'products',
        'Select product'                                        =>  'select_product',
        'Product Variants'                                      =>  'product_variants',
        'Select Variants'                                       =>  'select_variants',
        'Product Quantity'                                      =>  'product_quantity',
        'Get Barcode/Label'                                     =>  'get_barcode/label',
        'Print Barcode/Label'                                   =>  'print_barcode/label',
        'Print'                                                 =>  'print',
        'Price'                                                 =>  'price',
        'The Barcode/Label data not found'                      =>  'the_barcode_label_data_not_found',
        'Product Cost'                                          =>  'product_cost',
        'Product Price'                                         =>  'product_price',
        'Product Unit'                                          =>  'product_unit',
        'Select Unit'                                           =>  'select_unit',
        'Tax Rate'                                              =>  'tax_rate',
        'Select Tax Rate'                                       =>  'select_tax_rate',
        'Barcode'                                               =>  'barcode',
        'Barcode Type'                                          =>  'barcode_type',
        'Add Product'                                           =>  'add_product',
        'This product has multiple variants'                    =>  'this_product_has_multiple_variants',
        'Additional Price'                                      =>  'additional_price',
        'Update Product'                                        =>  'update_product',
        'Select Status'                                         =>  'select_status',
        'Unit'                                                  =>  'unit',
        'Cost'                                                  =>  'cost',
        'Category'                                              =>  'category',
        'Qrcode'                                                =>  'qrcode',
        'Create Date'                                           =>  'create_date',
        'Product Variations'                                    =>  'product_variations',
        'validation.attributes.profile'                         =>  'validationattributesprofile',
        'Change Password'                                       =>  'change_password',
        'Old Password'                                          =>  'old_password',
        'Password'                                              =>  'password',
        'Password Confirmation'                                 =>  'password_confirmation',
        'Save Password'                                         =>  'save_password',
        'profile image'                                         =>  'profile_image',
        'Add Purchase'                                          =>  'add_purchase',
        'Reference No'                                          =>  'reference_no',
        'Unit Price'                                            =>  'unit_price',
        'Quantity'                                              =>  'quantity',
        'Subtotal'                                              =>  'subtotal',
        'Note'                                                  =>  'note',
        'Purchase Edit'                                         =>  'purchase_edit',
        'Purchases'                                             =>  'purchases',
        'Purchases No'                                          =>  'purchases_no',
        'Purchases View'                                        =>  'purchases_view',
        'Phone:'                                                =>  'phone',
        'Email:'                                                =>  'email',
        'Reference No:'                                         =>  'reference_no',
        'Date:'                                                 =>  'date',
        'Create by'                                             =>  'create_by',
        'Purchases Report'                                      =>  'purchases_report',
        'From Date'                                             =>  'from_date',
        'To Date'                                               =>  'to_date',
        'Purchases Report '                                     =>  'purchases_report',
        'PurchaseNo'                                            =>  'purchaseno',
        'The purchase data not found'                           =>  'the_purchase_data_not_found',
        'Sales Report'                                          =>  'sales_report',
        'BilNo'                                                 =>  'bilno',
        'Order Tax'                                             =>  'order_tax',
        'Paid'                                                  =>  'paid',
        'The Sales data not found'                              =>  'the_sales_data_not_found',
        'Stock Report'                                          =>  'stock_report',
        'Stock Report '                                         =>  'stock_report',
        'Sale Qty'                                              =>  'sale_qty',
        'Total Qty'                                             =>  'total_qty',
        'Stock Qty'                                             =>  'stock_qty',
        'Income'                                                =>  'income',
        'The stock data not found'                              =>  'the_stock_data_not_found',
        'Roles'                                                 =>  'roles',
        'Add Role'                                              =>  'add_role',
        'Permission'                                            =>  'permission',
        'Module Name'                                           =>  'module_name',
        'Create'                                                =>  'create',
        'Edit'                                                  =>  'edit',
        'Delete'                                                =>  'delete',
        'Show'                                                  =>  'show',
        'Please add product'                                    =>  'please_add_product',
        'OK'                                                    =>  'ok',
        'Do you want to continue?'                              =>  'do_you_want_to_continue?',
        'Yes'                                                   =>  'yes',
        'Cancel'                                                =>  'cancel',
        'Update'                                                =>  'update',
        'Sales'                                                 =>  'sales',
        'Add POS'                                               =>  'add_pos',
        'SaleNo'                                                =>  'saleno',
        'Sales Person: '                                        =>  'sales_person',
        'Sale No:'                                              =>  'sale_no',
        'Customer:'                                             =>  'customer',
        'Cash/Credit'                                           =>  'cash_credit',
        'Description'                                           =>  'description',
        'Tax'                                                   =>  'tax',
        'Total Order Tax'                                       =>  'total_order_tax',
        'Total Amount'                                          =>  'total_amount',
        'Credit Amount'                                         =>  'credit_amount',
        'Cash Amount'                                           =>  'cash_amount',
        'Paid Amount'                                           =>  'paid_amount',
        'Amount:'                                               =>  'amount',
        'WhatsApp'                                              =>  'whatsapp',
        'Back to POS'                                           =>  'back_to_pos',
        'Please Select Shop'                                    =>  'please_select_shop',
        'Sales View'                                            =>  'sales_view',
        'Total Credit Amount'                                   =>  'total_credit_amount',
        'Total Cash Amount'                                     =>  'total_cash_amount',
        'Total Paid Amount'                                     =>  'total_paid_amount',
        'Email Setting'                                         =>  'email_setting',
        'Enable'                                                =>  'enable',
        'Disable'                                               =>  'disable',
        'Update Email Setting'                                  =>  'update_email_setting',
        'Settings'                                              =>  'settings',
        'Site Setting'                                          =>  'site_setting',
        'WhatsApp SMS Setting'                                  =>  'whatsapp_sms_setting',
        'SMS Setting'                                           =>  'sms_setting',
        'Payment Setting'                                       =>  'payment_setting',
        'Payment Type'                                          =>  'payment_type',
        'Stripe'                                                =>  'stripe',
        'Razorpay'                                              =>  'razorpay',
        'Stripe Setting'                                        =>  'stripe_setting',
        'Update Stripe Setting'                                 =>  'update_stripe_setting',
        'Razorpay Setting'                                      =>  'razorpay_setting',
        'Update Razorpay  Setting'                              =>  'update_razorpay_ setting',
        'General Setting'                                       =>  'general_setting',
        'Site Phone Number'                                     =>  'site_phone_number',
        'Choose'                                                =>  'choose',
        'Food Express Logo'                                     =>  'food_express_logo',
        'Update Site Setting'                                   =>  'update_site_setting',
        'Twilio Auth Token'                                     =>  'twilio_auth_token',
        '(Your Twilio WhatsApp number )'                        =>  'your_twilio_whatsapp_number',
        'Update Sms Setting'                                    =>  'update_sms_setting',
        'WATI Auth Token'                                       =>  'wati_auth_token',
        '(Your WATI WhatsApp Auth Token )'                      =>  'your_wati_whatsapp_auth_token',
        'WATI API Endpoint'                                     =>  'wati_api_endpoint',
        '(Your WATI WhatsApp Endpoint )'                        =>  'your_wati_whatsapp_endpoint',
        'WATI Template Name'                                    =>  'wati_template_name',
        '(Your WATI WhatsApp Template Name )'                   =>  'your_wati_whatsapp_template_name',
        'Update WhatsApp Sms Setting'                           =>  'update_whatsapp_sms_setting',
        'Shops'                                                 =>  'shops',
        'General'                                               =>  'general',
        'Shop Owner'                                            =>  'shop_owner',
        'Add Shop'                                              =>  'add_shop',
        'Deposit Amount'                                        =>  'deposit_amount',
        'Limit Amount'                                          =>  'limit_amount',
        'Stocks'                                                =>  'stocks',
        'Tax Rates'                                             =>  'tax_rates',
        'Code'                                                  =>  'code',
        'Type'                                                  =>  'type',
        'Add Tax'                                               =>  'add_tax',
        'Units'                                                 =>  'units',
        'Add Unit'                                              =>  'add_unit',
        'This is a secure area of the application. Please confirm your password before continuing.' 
                                                                =>  'secure_area_of_the_application',
        'Confirm'                                               =>  'confirm',
        'Forgot your password? No problem. Just let us know your email address and we will email you a password reset link that will allow you to choose a new one.'
                                                                =>  'forgot_your_password',
        'Email Password Reset Link'                             =>  'email_password_reset_link',
        'Login'                                                 =>  'login',
        'Remember Me'                                           =>  'remember_me',
        'For Quick Demo Login Click Below...'                   =>  'for_quick_demo_login_click_below',
        'Admin'                                                 =>  'admin',
        'Shop Owner Two'                                        =>  'shop_owner_two',
        'Confirm Password'                                      =>  'confirm_password',
        'Already registered?'                                   =>  'already_registered',
        'Register'                                              =>  'register',
        'Reset Password'                                        =>  'reset_password',
        "Thanks for signing up! Before getting started, could you verify your email address by clicking on the link we just emailed to you? If you didn't receive the email, we will gladly send you another."
                                                                =>  'thanks_for_signing_up',
        'A new verification link has been sent to the email address you provided during registration.' 
                                                                =>  'verification_link_has_been_sent',
        'Resend Verification Email'                             =>  'resend_verification_email',
        'Log Out'                                               =>  'log_out',
        'Whoops! Something went wrong.'                         =>  'whoops_something_went_wrong',
        'Welcome To'                                            =>  'welcome_to',
        'Register With Us'                                      =>  'register_with_us',
        'Register by Your WhatsApp Number'                      =>  'register_by_your_whatsapp_number',
        'Cash'                                                  =>  'cash',
        'Credit or debit card'                                  =>  'credit_or_debit_card',
        'Take Membership'                                       =>  'take_membership',
        'Find Your Balance'                                     =>  'find_your_balance',
        'Give your whatsapp number'                             =>  'give_your_whatsapp_number',
        'Check balance'                                         =>  'check_balance',
        'Balance'                                               =>  'balance',
        'Sorry,no customer available!'                          =>  'sorryno_customer_available!',
        'Dashboard'                                             =>  'dashboard',
        '( Example of country code phone number:+15129004889 )' =>  'example_of_country_code_phone_number',
        'Qty'                                                   =>  'qty',
        'Total Items'                                           =>  'total_items',
        'Customer First Name'                                   =>  'customer_first_name',
        'Customer Last Name'                                    =>  'customer_last_name',
        'Customer Deposit amount'                               =>  'customer_deposit_amount',
        'Payment'                                               =>  'payment',
        'Total Payable'                                         =>  'total_payable',
        'Total Customer Credit'                                 =>  'total_customer_credit',
        'Total Paying'                                          =>  'total_paying',
        'Close'                                                 =>  'close',
        'EDIT ORDER TAX'                                        =>  'edit_order_tax',
        'Order'                                                 =>  'order',
        'Bill'                                                  =>  'bill',
        'Merchant Copy'                                         =>  'merchant_copy',
    ];

    protected $files = [
        'resources\views\admin\administrators\create.blade.php',
        'resources\views\admin\administrators\edit.blade.php',
        'resources\views\admin\administrators\index.blade.php',
        'resources\views\admin\administrators\show.blade.php',
        'resources\views\admin\category\create.blade.php',
        'resources\views\admin\category\edit.blade.php',
        'resources\views\admin\category\index.blade.php',
        'resources\views\admin\customer\create.blade.php',
        'resources\views\admin\customer\edit.blade.php',
        'resources\views\admin\customer\index.blade.php',
        'resources\views\admin\customer\show.blade.php',
        'resources\views\admin\dashboard\index.blade.php',
        'resources\views\admin\deposit\create.blade.php',
        'resources\views\admin\deposit\edit.blade.php',
        'resources\views\admin\deposit\index.blade.php',
        'resources\views\admin\layouts\components\navigation.blade.php',
        'resources\views\admin\product\barcode.blade.php',
        'resources\views\admin\product\create.blade.php',
        'resources\views\admin\product\edit.blade.php',
        'resources\views\admin\product\index.blade.php',
        'resources\views\admin\product\show.blade.php',
        'resources\views\admin\profile\index.blade.php',
        'resources\views\admin\purchase\create.blade.php',
        'resources\views\admin\purchase\edit.blade.php',
        'resources\views\admin\purchase\index.blade.php',
        'resources\views\admin\purchase\show.blade.php',
        'resources\views\admin\report\purchase.blade.php',
        'resources\views\admin\report\sale.blade.php',
        'resources\views\admin\report\stock.blade.php',
        'resources\views\admin\role\create.blade.php',
        'resources\views\admin\role\edit.blade.php',
        'resources\views\admin\role\index.blade.php',
        'resources\views\admin\role\show.blade.php',
        'resources\views\admin\sale\create.blade.php',
        'resources\views\admin\sale\edit.blade.php',
        'resources\views\admin\sale\index.blade.php',
        'resources\views\admin\sale\print.blade.php',
        'resources\views\admin\sale\shop.blade.php',
        'resources\views\admin\sale\show.blade.php',
        'resources\views\admin\setting\email.blade.php',
        'resources\views\admin\setting\index.blade.php',
        'resources\views\admin\setting\payment.blade.php',
        'resources\views\admin\setting\site.blade.php',
        'resources\views\admin\setting\sms.blade.php',
        'resources\views\admin\setting\whatsapp.blade.php',
        'resources\views\admin\shop\create.blade.php',
        'resources\views\admin\shop\edit.blade.php',
        'resources\views\admin\shop\index.blade.php',
        'resources\views\admin\shop\show.blade.php',
        'resources\views\admin\stock\index.blade.php',
        'resources\views\admin\tax\create.blade.php',
        'resources\views\admin\tax\edit.blade.php',
        'resources\views\admin\tax\index.blade.php',
        'resources\views\admin\unit\create.blade.php',
        'resources\views\admin\unit\edit.blade.php',
        'resources\views\admin\unit\index.blade.php',
        'resources\views\auth\confirm-password.blade.php',
        'resources\views\auth\forgot-password.blade.php',
        'resources\views\auth\login.blade.php',
        'resources\views\auth\register.blade.php',
        'resources\views\auth\reset-password.blade.php',
        'resources\views\auth\verify-email.blade.php',
        'resources\views\components\auth-validation-errors.blade.php',
        'resources\views\frontend\check-in\home.blade.php',
        'resources\views\frontend\check-in\step-one.blade.php',
        'resources\views\frontend\customer\index.blade.php',
        'resources\views\frontend\layouts\partials\_nav.blade.php',
        'resources\views\layouts\navigation.blade.php',
        'resources\views\livewire\customer-post-form.blade.php',
        'resources\views\livewire\pos-form.blade.php',
        'resources\views\livewire\pos-model\add-customer.blade.php',
        'resources\views\livewire\pos-model\add-payment.blade.php',
        'resources\views\livewire\pos-model\edit-cart-item.blade.php',
        'resources\views\livewire\pos-model\order-tax.blade.php',
        'resources\views\livewire\pos-model\print-order.blade.php',
    ];



    /**
     * Create a new command instance.
     *
     * @return void
     */
    public function __construct()
    {
        parent::__construct();
    }

    /**
     * Execute the console command.
     *
     * @return int
     */
    public function handle()
    {
        foreach ($this->files as $file) {
            foreach ($this->toReplace as $old => $new) {
                $fileName = self::BASE_PATH . $file;
                $content = file_get_contents($fileName);
                $newContent = str_replace("__('levels.$old')", "__('levels.$new')", $content);
                file_put_contents($fileName, $newContent);
            }
        }
    }
}